# SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
from os import PathLike

from ..._surge import _DynamicModel as DynamicModel


def load(path: str | PathLike[str]) -> DynamicModel: ...
def loads(content: str) -> DynamicModel: ...
def save(model: DynamicModel, path: str | PathLike[str]) -> None: ...
def dumps(model: DynamicModel) -> str: ...
